package io.github.xhuohai.sudo.utils

/**
 * Comprehensive emoji shortcode to Unicode conversion
 * Based on Discourse/GitHub emoji shortcodes
 */
object EmojiUtils {
    
    private val emojiMap = mapOf(
        // ===== SMILEYS & EMOTION =====
        ":grinning:" to "😀", ":smiley:" to "😃", ":smile:" to "😄", ":grin:" to "😁",
        ":laughing:" to "😆", ":satisfied:" to "😆", ":sweat_smile:" to "😅", 
        ":rofl:" to "🤣", ":joy:" to "😂", ":slightly_smiling_face:" to "🙂",
        ":upside_down_face:" to "🙃", ":wink:" to "😉", ":blush:" to "😊",
        ":innocent:" to "😇", ":smiling_face_with_three_hearts:" to "🥰",
        ":heart_eyes:" to "😍", ":star_struck:" to "🤩", ":kissing_heart:" to "😘",
        ":kissing:" to "😗", ":relaxed:" to "☺️", ":kissing_closed_eyes:" to "😚",
        ":kissing_smiling_eyes:" to "😙", ":smiling_face_with_tear:" to "🥲",
        ":yum:" to "😋", ":stuck_out_tongue:" to "😛", ":stuck_out_tongue_winking_eye:" to "😜",
        ":zany_face:" to "🤪", ":stuck_out_tongue_closed_eyes:" to "😝", ":money_mouth_face:" to "🤑",
        ":hugs:" to "🤗", ":hand_over_mouth:" to "🤭", ":shushing_face:" to "🤫",
        ":thinking:" to "🤔", ":zipper_mouth_face:" to "🤐", ":raised_eyebrow:" to "🤨",
        ":neutral_face:" to "😐", ":expressionless:" to "😑", ":no_mouth:" to "😶",
        ":smirk:" to "😏", ":unamused:" to "😒", ":roll_eyes:" to "🙄", ":rolling_eyes:" to "🙄",
        ":grimacing:" to "😬", ":lying_face:" to "🤥", ":relieved:" to "😌",
        ":pensive:" to "😔", ":sleepy:" to "😪", ":drooling_face:" to "🤤",
        ":sleeping:" to "😴", ":mask:" to "😷", ":face_with_thermometer:" to "🤒",
        ":face_with_head_bandage:" to "🤕", ":nauseated_face:" to "🤢", ":vomiting_face:" to "🤮",
        ":sneezing_face:" to "🤧", ":hot_face:" to "🥵", ":cold_face:" to "🥶",
        ":woozy_face:" to "🥴", ":dizzy_face:" to "😵", ":exploding_head:" to "🤯",
        ":cowboy_hat_face:" to "🤠", ":partying_face:" to "🥳", ":disguised_face:" to "🥸",
        ":sunglasses:" to "😎", ":nerd_face:" to "🤓", ":monocle_face:" to "🧐",
        ":confused:" to "😕", ":worried:" to "😟", ":slightly_frowning_face:" to "🙁",
        ":frowning_face:" to "☹️", ":open_mouth:" to "😮", ":hushed:" to "😯",
        ":astonished:" to "😲", ":flushed:" to "😳", ":pleading_face:" to "🥺",
        ":frowning:" to "😦", ":anguished:" to "😧", ":fearful:" to "😨",
        ":cold_sweat:" to "😰", ":disappointed_relieved:" to "😥", ":cry:" to "😢",
        ":sob:" to "😭", ":scream:" to "😱", ":confounded:" to "😖",
        ":persevere:" to "😣", ":disappointed:" to "😞", ":sweat:" to "😓",
        ":weary:" to "😩", ":tired_face:" to "😫", ":yawning_face:" to "🥱",
        ":triumph:" to "😤", ":rage:" to "😡", ":angry:" to "😠",
        ":cursing_face:" to "🤬", ":smiling_imp:" to "😈", ":imp:" to "👿",
        ":skull:" to "💀", ":skull_and_crossbones:" to "☠️", ":poop:" to "💩",
        ":clown_face:" to "🤡", ":japanese_ogre:" to "👹", ":japanese_goblin:" to "👺",
        ":ghost:" to "👻", ":alien:" to "👽", ":space_invader:" to "👾",
        ":robot:" to "🤖", ":smiley_cat:" to "😺", ":smile_cat:" to "😸",
        ":joy_cat:" to "😹", ":heart_eyes_cat:" to "😻", ":smirk_cat:" to "😼",
        ":kissing_cat:" to "😽", ":scream_cat:" to "🙀", ":crying_cat_face:" to "😿",
        ":pouting_cat:" to "😾", ":see_no_evil:" to "🙈", ":hear_no_evil:" to "🙉",
        ":speak_no_evil:" to "🙊",
        
        // Short aliases
        ":)" to "🙂", ":D" to "😀", ";)" to "😉", ":P" to "😛",
        ":(" to "🙁", ":'(" to "😢", ":O" to "😮", ":|" to "😐",
        
        // ===== GESTURES & BODY =====
        ":wave:" to "👋", ":raised_back_of_hand:" to "🤚", ":raised_hand:" to "✋",
        ":vulcan_salute:" to "🖖", ":ok_hand:" to "👌", ":pinched_fingers:" to "🤌",
        ":pinching_hand:" to "🤏", ":v:" to "✌️", ":crossed_fingers:" to "🤞",
        ":love_you_gesture:" to "🤟", ":metal:" to "🤘", ":call_me_hand:" to "🤙",
        ":point_left:" to "👈", ":point_right:" to "👉", ":point_up_2:" to "👆",
        ":middle_finger:" to "🖕", ":point_down:" to "👇", ":point_up:" to "☝️",
        ":+1:" to "👍", ":thumbsup:" to "👍", ":-1:" to "👎", ":thumbsdown:" to "👎",
        ":fist:" to "✊", ":facepunch:" to "👊", ":punch:" to "👊",
        ":fist_left:" to "🤛", ":fist_right:" to "🤜", ":clap:" to "👏",
        ":raised_hands:" to "🙌", ":open_hands:" to "👐", ":palms_up_together:" to "🤲",
        ":handshake:" to "🤝", ":pray:" to "🙏", ":writing_hand:" to "✍️",
        ":nail_care:" to "💅", ":selfie:" to "🤳", ":muscle:" to "💪",
        ":mechanical_arm:" to "🦾", ":mechanical_leg:" to "🦿", ":leg:" to "🦵",
        ":foot:" to "🦶", ":ear:" to "👂", ":nose:" to "👃",
        ":brain:" to "🧠", ":eyes:" to "👀", ":eye:" to "👁️",
        ":tongue:" to "👅", ":lips:" to "👄", ":baby:" to "👶",
        
        // ===== HEARTS & LOVE =====
        ":heart:" to "❤️", ":red_heart:" to "❤️", ":orange_heart:" to "🧡",
        ":yellow_heart:" to "💛", ":green_heart:" to "💚", ":blue_heart:" to "💙",
        ":purple_heart:" to "💜", ":black_heart:" to "🖤", ":brown_heart:" to "🤎",
        ":white_heart:" to "🤍", ":broken_heart:" to "💔", ":heart_exclamation:" to "❣️",
        ":two_hearts:" to "💕", ":revolving_hearts:" to "💞", ":heartbeat:" to "💓",
        ":heartpulse:" to "💗", ":sparkling_heart:" to "💖", ":cupid:" to "💘",
        ":gift_heart:" to "💝", ":heart_decoration:" to "💟", ":peace_symbol:" to "☮️",
        ":latin_cross:" to "✝️", ":star_of_david:" to "✡️", ":om:" to "🕉️",
        ":kiss:" to "💋", ":love_letter:" to "💌", ":ring:" to "💍",
        ":gem:" to "💎", ":bouquet:" to "💐", ":couple_with_heart:" to "💑",
        
        // ===== SYMBOLS & OBJECTS =====
        ":fire:" to "🔥", ":100:" to "💯", ":star:" to "⭐", ":star2:" to "🌟",
        ":sparkles:" to "✨", ":dizzy:" to "💫", ":boom:" to "💥", ":collision:" to "💥",
        ":anger:" to "💢", ":exclamation:" to "❗", ":question:" to "❓",
        ":grey_exclamation:" to "❕", ":grey_question:" to "❔", ":zzz:" to "💤",
        ":dash:" to "💨", ":sweat_drops:" to "💦", ":notes:" to "🎶",
        ":musical_note:" to "🎵", ":speech_balloon:" to "💬", ":thought_balloon:" to "💭",
        ":bulb:" to "💡", ":moneybag:" to "💰", ":dollar:" to "💵",
        ":money_with_wings:" to "💸", ":credit_card:" to "💳",
        ":email:" to "📧", ":e-mail:" to "📧", ":envelope:" to "✉️",
        ":incoming_envelope:" to "📨", ":love_letter:" to "💌",
        ":phone:" to "📱", ":telephone_receiver:" to "📞", ":pager:" to "📟",
        ":computer:" to "💻", ":desktop_computer:" to "🖥️", ":keyboard:" to "⌨️",
        ":tv:" to "📺", ":camera:" to "📷", ":video_camera:" to "📹",
        ":movie_camera:" to "🎥", ":clapper:" to "🎬", ":headphones:" to "🎧",
        ":microphone:" to "🎤", ":battery:" to "🔋", ":electric_plug:" to "🔌",
        ":mag:" to "🔍", ":mag_right:" to "🔎", ":lock:" to "🔒", ":unlock:" to "🔓",
        ":key:" to "🔑", ":hammer:" to "🔨", ":axe:" to "🪓", ":wrench:" to "🔧",
        ":nut_and_bolt:" to "🔩", ":gear:" to "⚙️", ":chains:" to "⛓️",
        ":gun:" to "🔫", ":bomb:" to "💣", ":kitchen_knife:" to "🔪",
        ":link:" to "🔗", ":paperclip:" to "📎", ":scissors:" to "✂️",
        ":file_folder:" to "📁", ":open_file_folder:" to "📂",
        ":calendar:" to "📅", ":date:" to "📅", ":clipboard:" to "📋",
        ":pushpin:" to "📌", ":round_pushpin:" to "📍", ":straight_ruler:" to "📏",
        ":triangular_ruler:" to "📐", ":pencil2:" to "✏️", ":black_nib:" to "✒️",
        ":memo:" to "📝", ":pencil:" to "📝", ":notebook:" to "📓",
        ":book:" to "📖", ":books:" to "📚", ":newspaper:" to "📰",
        ":bookmark:" to "🔖", ":label:" to "🏷️", ":trophy:" to "🏆",
        ":medal_sports:" to "🏅", ":1st_place_medal:" to "🥇", ":2nd_place_medal:" to "🥈",
        ":3rd_place_medal:" to "🥉", ":crown:" to "👑",
        
        // ===== CHECK MARKS & CONTROLS =====
        ":white_check_mark:" to "✅", ":ballot_box_with_check:" to "☑️",
        ":heavy_check_mark:" to "✔️", ":x:" to "❌", ":negative_squared_cross_mark:" to "❎",
        ":o:" to "⭕", ":heavy_plus_sign:" to "➕", ":heavy_minus_sign:" to "➖",
        ":heavy_division_sign:" to "➗", ":heavy_multiplication_x:" to "✖️",
        ":warning:" to "⚠️", ":no_entry:" to "⛔", ":no_entry_sign:" to "🚫",
        ":radioactive:" to "☢️", ":biohazard:" to "☣️", ":arrow_up:" to "⬆️",
        ":arrow_down:" to "⬇️", ":arrow_left:" to "⬅️", ":arrow_right:" to "➡️",
        ":left_right_arrow:" to "↔️", ":arrow_up_down:" to "↕️",
        ":repeat:" to "🔁", ":repeat_one:" to "🔂", ":arrows_counterclockwise:" to "🔄",
        ":recycle:" to "♻️", ":infinity:" to "♾️", ":copyright:" to "©️",
        ":registered:" to "®️", ":tm:" to "™️",
        
        // ===== NATURE & ANIMALS =====
        ":sun:" to "☀️", ":sun_with_face:" to "🌞", ":moon:" to "🌙",
        ":full_moon:" to "🌕", ":new_moon:" to "🌑", ":cloud:" to "☁️",
        ":rain_cloud:" to "🌧️", ":thunder_cloud_and_rain:" to "⛈️",
        ":rainbow:" to "🌈", ":snowflake:" to "❄️", ":snowman:" to "⛄",
        ":zap:" to "⚡", ":tornado:" to "🌪️", ":fog:" to "🌫️",
        ":ocean:" to "🌊", ":droplet:" to "💧", ":umbrella:" to "☔",
        ":rose:" to "🌹", ":sunflower:" to "🌻", ":tulip:" to "🌷",
        ":cherry_blossom:" to "🌸", ":hibiscus:" to "🌺", ":herb:" to "🌿",
        ":leaves:" to "🍃", ":four_leaf_clover:" to "🍀", ":seedling:" to "🌱",
        ":evergreen_tree:" to "🌲", ":deciduous_tree:" to "🌳", ":palm_tree:" to "🌴",
        ":cactus:" to "🌵", ":mushroom:" to "🍄", ":chestnut:" to "🌰",
        ":dog:" to "🐶", ":cat:" to "🐱", ":mouse:" to "🐭", ":hamster:" to "🐹",
        ":rabbit:" to "🐰", ":fox_face:" to "🦊", ":bear:" to "🐻",
        ":panda_face:" to "🐼", ":koala:" to "🐨", ":tiger:" to "🐯",
        ":lion:" to "🦁", ":cow:" to "🐮", ":pig:" to "🐷", ":frog:" to "🐸",
        ":monkey_face:" to "🐵", ":chicken:" to "🐔", ":penguin:" to "🐧",
        ":bird:" to "🐦", ":hatching_chick:" to "🐣", ":eagle:" to "🦅",
        ":duck:" to "🦆", ":owl:" to "🦉", ":bat:" to "🦇",
        ":wolf:" to "🐺", ":boar:" to "🐗", ":horse:" to "🐴",
        ":unicorn:" to "🦄", ":bee:" to "🐝", ":bug:" to "🐛",
        ":butterfly:" to "🦋", ":snail:" to "🐌", ":lady_beetle:" to "🐞",
        ":ant:" to "🐜", ":mosquito:" to "🦟", ":spider:" to "🕷️",
        ":turtle:" to "🐢", ":snake:" to "🐍", ":lizard:" to "🦎",
        ":scorpion:" to "🦂", ":crab:" to "🦀", ":shrimp:" to "🦐",
        ":squid:" to "🦑", ":octopus:" to "🐙", ":fish:" to "🐟",
        ":tropical_fish:" to "🐠", ":blowfish:" to "🐡", ":shark:" to "🦈",
        ":whale:" to "🐳", ":whale2:" to "🐋", ":dolphin:" to "🐬",
        ":elephant:" to "🐘", ":rhino:" to "🦏", ":hippopotamus:" to "🦛",
        ":camel:" to "🐫", ":giraffe:" to "🦒", ":kangaroo:" to "🦘",
        ":dragon:" to "🐉", ":dragon_face:" to "🐲", ":t_rex:" to "🦖",
        
        // ===== FOOD & DRINK =====
        ":apple:" to "🍎", ":green_apple:" to "🍏", ":pear:" to "🍐",
        ":orange:" to "🍊", ":lemon:" to "🍋", ":banana:" to "🍌",
        ":watermelon:" to "🍉", ":grapes:" to "🍇", ":strawberry:" to "🍓",
        ":melon:" to "🍈", ":cherries:" to "🍒", ":peach:" to "🍑",
        ":mango:" to "🥭", ":pineapple:" to "🍍", ":coconut:" to "🥥",
        ":kiwi_fruit:" to "🥝", ":tomato:" to "🍅", ":eggplant:" to "🍆",
        ":avocado:" to "🥑", ":broccoli:" to "🥦", ":carrot:" to "🥕",
        ":corn:" to "🌽", ":hot_pepper:" to "🌶️", ":cucumber:" to "🥒",
        ":potato:" to "🥔", ":sweet_potato:" to "🍠", ":bread:" to "🍞",
        ":croissant:" to "🥐", ":baguette_bread:" to "🥖", ":pretzel:" to "🥨",
        ":cheese:" to "🧀", ":egg:" to "🥚", ":cooking:" to "🍳",
        ":pancakes:" to "🥞", ":waffle:" to "🧇", ":bacon:" to "🥓",
        ":cut_of_meat:" to "🥩", ":poultry_leg:" to "🍗", ":meat_on_bone:" to "🍖",
        ":hamburger:" to "🍔", ":fries:" to "🍟", ":pizza:" to "🍕",
        ":hot_dog:" to "🌭", ":sandwich:" to "🥪", ":taco:" to "🌮",
        ":burrito:" to "🌯", ":stuffed_flatbread:" to "🥙", ":falafel:" to "🧆",
        ":ramen:" to "🍜", ":spaghetti:" to "🍝", ":curry:" to "🍛",
        ":sushi:" to "🍣", ":fried_shrimp:" to "🍤", ":rice:" to "🍚",
        ":rice_ball:" to "🍙", ":rice_cracker:" to "🍘", ":fish_cake:" to "🍥",
        ":dango:" to "🍡", ":oden:" to "🍢", ":ice_cream:" to "🍨",
        ":doughnut:" to "🍩", ":cookie:" to "🍪", ":birthday:" to "🎂",
        ":cake:" to "🍰", ":cupcake:" to "🧁", ":pie:" to "🥧",
        ":chocolate_bar:" to "🍫", ":candy:" to "🍬", ":lollipop:" to "🍭",
        ":honey_pot:" to "🍯", ":coffee:" to "☕", ":tea:" to "🍵",
        ":sake:" to "🍶", ":champagne:" to "🍾", ":wine_glass:" to "🍷",
        ":cocktail:" to "🍸", ":tropical_drink:" to "🍹", ":beer:" to "🍺",
        ":beers:" to "🍻", ":clinking_glasses:" to "🥂", ":tumbler_glass:" to "🥃",
        ":cup_with_straw:" to "🥤", ":milk_glass:" to "🥛",
        
        // ===== ACTIVITIES & CELEBRATIONS =====
        ":tada:" to "🎉", ":confetti_ball:" to "🎊", ":balloon:" to "🎈",
        ":gift:" to "🎁", ":ribbon:" to "🎀", ":sparkler:" to "🎇",
        ":fireworks:" to "🎆", ":jack_o_lantern:" to "🎃", ":ghost:" to "👻",
        ":christmas_tree:" to "🎄", ":santa:" to "🎅", ":snowman:" to "⛄",
        ":rocket:" to "🚀", ":airplane:" to "✈️", ":car:" to "🚗",
        ":bike:" to "🚲", ":ship:" to "🚢", ":anchor:" to "⚓",
        
        // ===== CHINESE / FESTIVAL =====
        ":red_envelope:" to "🧧", ":firecracker:" to "🧨", ":moon_cake:" to "🥮",
        ":dumpling:" to "🥟", ":fortune_cookie:" to "🥠", ":takeout_box:" to "🥡",
        ":chopsticks:" to "🥢", ":bento:" to "🍱", ":tanabata_tree:" to "🎋",
        ":bamboo:" to "🎍", ":dolls:" to "🎎", ":flags:" to "🎏",
        ":wind_chime:" to "🎐", ":rice_scene:" to "🎑", ":lantern:" to "🏮",
        ":izakaya_lantern:" to "🏮", ":envelope_with_arrow:" to "📩",
        
        // ===== TECH & CODING =====
        ":octocat:" to "🐙", ":shipit:" to "🐿️", ":neckbeard:" to "🧔",
        ":trollface:" to "👹", ":godmode:" to "😎", ":rage1:" to "😡",
        ":rage2:" to "😤", ":rage3:" to "🤬", ":rage4:" to "💢",
        ":suspect:" to "🕵️", ":finnadie:" to "😵", ":goberserk:" to "🤯",
        ":feelsgood:" to "😌", ":hurtrealbad:" to "😫"
    )
    
    fun convertShortcodes(text: String): String {
        var result = text
        for ((shortcode, emoji) in emojiMap) {
            result = result.replace(shortcode, emoji)
        }
        return result
    }
}
